import { GoogleGenAI } from "@google/genai";

// Initialize Gemini AI
// Note: In a production app, you might want to proxy this through your backend
// to keep your API key secure, or use the AI Studio injected key in the frontend
// as we are doing here for the preview environment.
export const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function validateFace(base64Image: string): Promise<{ isValid: boolean; reason: string }> {
  try {
    const model = "gemini-2.5-flash-image";
    const prompt = `
      Analyze this image. Does it contain a clear, visible human face that could be used for a face-swap meme?
      Ignore cartoons, drawings, or blurry faces. It must be a real human face.
      Return ONLY a JSON object with this structure:
      {
        "isValid": boolean,
        "reason": "short explanation"
      }
    `;

    const response = await ai.models.generateContent({
      model,
      contents: {
        parts: [
          { inlineData: { mimeType: "image/jpeg", data: base64Image } },
          { text: prompt }
        ]
      }
    });

    const text = response.text;
    if (!text) throw new Error("No response from AI");
    
    // Clean up potential markdown code blocks
    const cleanText = text.replace(/```json\n?|\n?```/g, '').trim();
    const result = JSON.parse(cleanText);
    return result;
  } catch (error) {
    console.error("Face validation error:", error);
    // Return false instead of a success fallback to ensure we explicitly rely on the AI check
    return { isValid: false, reason: "Could not validate face with AI. Please try again." };
  }
}

export async function generateMeme(faceBase64: string, templateBase64: string): Promise<string> {
  try {
    const model = "gemini-2.5-flash-image";
    const prompt = `
      Create a high-quality meme image.
      1. Take the face from the first image (the user's selfie).
      2. Place it onto the character's face in the second image (the meme template).
      3. Blend it naturally so it looks like the user is the character in the meme.
      4. Maintain the original meme's style, lighting, and resolution.
      5. Return ONLY the generated image.
    `;

    // Note: In a real production environment, we would use 'generateImages' or a specific image editing endpoint.
    // However, for this prototype using the standard generateContent with image output:
    const response = await ai.models.generateContent({
      model,
      contents: {
        parts: [
          { inlineData: { mimeType: "image/jpeg", data: faceBase64 } },
          { inlineData: { mimeType: "image/jpeg", data: templateBase64 } },
          { text: prompt }
        ]
      }
    });

    // Extract image from response
    // The model might return text or image. We need to handle the image part.
    // Note: The current SDK/Model version might return the image in a specific way.
    // For this prototype, if the model returns text instead of an image (common in some versions),
    // we will throw to trigger the fallback UI.
    
    // Check for inline data in parts
    const candidates = response.candidates;
    if (candidates && candidates[0].content.parts) {
      for (const part of candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by AI");
  } catch (error) {
    console.error("AI Generation error:", error);
    throw error;
  }
}
